### ISSUE TITLE
LOW VERSION gcc in all-build.sh

### ISSUE THREAD

**Issue by FFreestanding** [Minep/lunaix-os#15]
lunaix-os/slides/c0-workspace/all-build.sh will install a lower version of gcc. So the project doesn't build properly.
### solution
We could keep the process of building qemu in all-build.sh.Running bochs-build.sh and gcc-build.sh to build other tools.

**Comment by Minep** [comment]
Thanks for the report.

This is indeed an issue as the script is trying to install gcc 10 instead of recommended gcc 11+. 

I believe there is a switch defined in the script to allow you to cherry-pick the installing component, but I need to check. I will aim to update the script and bring you more information later today.
